from flask import Blueprint, Response, jsonify
from config import supabase
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_RIGHT, TA_CENTER
from reportlab.pdfgen import canvas as rl_canvas
import io
from datetime import datetime, timedelta

invoice_pdf_bp = Blueprint('invoice_pdf', __name__)

# ── Brand colours ──────────────────────────────────────────
DARK    = colors.HexColor('#1e1e2e')
INDIGO  = colors.HexColor('#6366f1')
INDIGO_L= colors.HexColor('#e0e7ff')
EMERALD = colors.HexColor('#10b981')
SLATE   = colors.HexColor('#64748b')
LIGHT   = colors.HexColor('#f8f8fc')
WHITE   = colors.white
BLACK   = colors.HexColor('#0f172a')


# ── Numbered-canvas for page footer ────────────────────────
class InvoiceCanvas(rl_canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self._draw_footer()
            super().showPage()
        super().save()

    def _draw_footer(self):
        W, H = A4
        # dark footer bar
        self.setFillColor(DARK)
        self.rect(0, 0, W, 20 * mm, fill=1, stroke=0)
        self.setFont('Helvetica', 7)
        self.setFillColor(colors.HexColor('#9090b0'))
        self.drawCentredString(
            W / 2, 8 * mm,
            'Generated by ConstructOS  |  Samarth Developers  |  Confidential'
        )


def _para(text, size=9, color=BLACK, bold=False, align=TA_LEFT, leading=None):
    return Paragraph(text, ParagraphStyle(
        'x',
        fontSize=size,
        textColor=color,
        fontName='Helvetica-Bold' if bold else 'Helvetica',
        alignment=align,
        leading=leading or size * 1.4,
        spaceAfter=0,
    ))


@invoice_pdf_bp.route('/<invoice_id>/pdf', methods=['GET'])
def download_invoice_pdf(invoice_id):
    # ── 1. Fetch data ──────────────────────────────────────
    try:
        res = supabase.table('invoices') \
            .select('*, invoice_items(*, materials(name, unit))') \
            .eq('id', invoice_id).single().execute()
        inv = res.data
    except Exception as e:
        return jsonify({'error': str(e)}), 404

    try:
        proj_res = supabase.table('projects') \
            .select('name, site_location') \
            .eq('id', inv['project_id']).single().execute()
        project = proj_res.data
    except Exception:
        project = {'name': 'N/A', 'site_location': ''}

    # ── 2. Derived values ──────────────────────────────────
    items      = inv.get('invoice_items') or []
    total      = float(inv.get('total_amount', 0))
    subtotal   = round(total / 1.18, 2)
    gst        = round(total - subtotal, 2)
    status     = (inv.get('status') or 'draft').upper()
    inv_num    = inv.get('invoice_number', 'INV-000000')
    created_dt = datetime.fromisoformat(
        inv['created_at'].replace('Z', '+00:00')
    ) if inv.get('created_at') else datetime.now()
    due_dt     = created_dt + timedelta(days=30)
    date_str   = created_dt.strftime('%d %B %Y')
    due_str    = due_dt.strftime('%d %B %Y')

    status_color = {
        'PAID': EMERALD,
        'SENT': INDIGO,
        'DRAFT': SLATE,
    }.get(status, SLATE)

    # ── 3. Build PDF in memory ─────────────────────────────
    buf  = io.BytesIO()
    W, H = A4
    m    = 18 * mm  # margin

    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=m, rightMargin=m,
        topMargin=58 * mm,    # space for drawn header
        bottomMargin=26 * mm, # space for footer
        title=f'Invoice {inv_num}',
        author='ConstructOS',
    )

    # ── 4. Header drawn on every page ─────────────────────
    def draw_header(canvas, doc):
        canvas.saveState()

        # dark band
        canvas.setFillColor(DARK)
        canvas.rect(0, H - 52 * mm, W, 52 * mm, fill=1, stroke=0)

        # indigo accent stripe
        canvas.setFillColor(INDIGO)
        canvas.rect(0, H - 55 * mm, W, 3 * mm, fill=1, stroke=0)

        # company name
        canvas.setFont('Helvetica-Bold', 20)
        canvas.setFillColor(WHITE)
        canvas.drawString(m, H - 22 * mm, 'CONSTRUCTOS')

        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(colors.HexColor('#b0b0d0'))
        canvas.drawString(m, H - 29 * mm, 'SAMARTH DEVELOPERS')
        canvas.drawString(m, H - 35 * mm, project.get('site_location', ''))

        # INVOICE label
        canvas.setFont('Helvetica-Bold', 26)
        canvas.setFillColor(INDIGO)
        canvas.drawRightString(W - m, H - 22 * mm, 'INVOICE')

        canvas.setFont('Helvetica', 9)
        canvas.setFillColor(colors.HexColor('#b0b0d0'))
        canvas.drawRightString(W - m, H - 30 * mm, inv_num)

        # status badge
        bw, bh = 24 * mm, 7 * mm
        bx = W - m - bw
        by = H - 40 * mm
        canvas.setFillColor(status_color)
        canvas.roundRect(bx, by, bw, bh, 2 * mm, fill=1, stroke=0)
        canvas.setFont('Helvetica-Bold', 7)
        canvas.setFillColor(WHITE)
        canvas.drawCentredString(bx + bw / 2, by + 2.2 * mm, status)

        # meta row
        meta = [
            ('INVOICE DATE', date_str),
            ('DUE DATE',     due_str),
            ('PROJECT',      project.get('name', 'N/A')[:22]),
        ]
        mx = m
        for label, val in meta:
            canvas.setFont('Helvetica-Bold', 6.5)
            canvas.setFillColor(colors.HexColor('#9090b0'))
            canvas.drawString(mx, H - 60 * mm + 4 * mm, label)
            canvas.setFont('Helvetica-Bold', 8.5)
            canvas.setFillColor(WHITE)
            canvas.drawString(mx, H - 60 * mm - 1 * mm, val)
            mx += 62 * mm

        canvas.restoreState()

    # ── 5. Flowable story ──────────────────────────────────
    story = []

    # section title
    story.append(_para('ITEMISED BILL OF MATERIALS', size=8,
                        color=SLATE, bold=True))
    story.append(Spacer(1, 3 * mm))

    # items table
    col_w = [10 * mm, 72 * mm, 18 * mm, 34 * mm, 34 * mm]
    tdata = [[
        _para('#',           bold=True, align=TA_CENTER, color=WHITE, size=8),
        _para('Description', bold=True, color=WHITE, size=8),
        _para('Qty',         bold=True, align=TA_CENTER, color=WHITE, size=8),
        _para('Unit Price',  bold=True, align=TA_RIGHT,  color=WHITE, size=8),
        _para('Amount',      bold=True, align=TA_RIGHT,  color=WHITE, size=8),
    ]]

    for idx, item in enumerate(items, 1):
        mat_name = ''
        if item.get('materials'):
            mat_name = item['materials'].get('name', '')
        desc = item.get('description') or mat_name or 'Material Supply'
        unit = (item.get('materials') or {}).get('unit', '')
        qty  = float(item.get('quantity', 0))
        up   = float(item.get('unit_price', 0))
        amt  = qty * up
        bg   = LIGHT if idx % 2 == 0 else WHITE
        tdata.append([
            _para(str(idx), align=TA_CENTER, size=8.5),
            _para(f'{desc}' + (f'<br/><font size="7" color="#94a3b8">{mat_name} · {unit}</font>'
                                if mat_name and mat_name != desc else ''), size=8.5),
            _para(f'{qty:g}', align=TA_CENTER, size=8.5),
            _para(f'Rs {up:,.2f}', align=TA_RIGHT, size=8.5),
            _para(f'Rs {amt:,.2f}', align=TA_RIGHT, size=8.5),
        ])

    t = Table(tdata, colWidths=col_w, repeatRows=1)
    t.setStyle(TableStyle([
        # header row
        ('BACKGROUND',   (0, 0), (-1, 0), DARK),
        ('ROWBACKGROUNDS',(0, 1), (-1, -1), [WHITE, LIGHT]),
        ('BOX',          (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e2ee')),
        ('INNERGRID',    (0, 0), (-1, -1), 0.3, colors.HexColor('#e2e2ee')),
        ('TOPPADDING',   (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING',(0, 0), (-1, -1), 4),
        ('LEFTPADDING',  (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
        ('VALIGN',       (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(t)
    story.append(Spacer(1, 6 * mm))

    # totals block – right-aligned table
    def money(label, val, bold=False, highlight=False):
        lc = WHITE if highlight else (BLACK if bold else SLATE)
        vc = WHITE if highlight else BLACK
        return [
            _para(label, bold=bold, color=lc, align=TA_LEFT,  size=9),
            _para(f'Rs {val:,.2f}', bold=bold, color=vc, align=TA_RIGHT, size=9),
        ]

    totals_data = [
        money('Subtotal (excl. GST 18%)', subtotal),
        money('GST @ 18%',                gst),
        money('TOTAL PAYABLE',            total, bold=True, highlight=True),
    ]
    totals_w = [90 * mm, 40 * mm]
    tt = Table(totals_data, colWidths=totals_w)
    tt.setStyle(TableStyle([
        ('ALIGN',        (0, 0), (-1, -1), 'LEFT'),
        ('TOPPADDING',   (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING',(0, 0), (-1, -1), 5),
        ('LEFTPADDING',  (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('LINEABOVE',    (0, 2), (-1, 2),  0.5, INDIGO),
        ('BACKGROUND',   (0, 2), (-1, 2),  DARK),
        ('ROWBACKGROUNDS',(0, 0), (-1, 1), [INDIGO_L, WHITE]),
        ('BOX',          (0, 0), (-1, -1), 0.5, colors.HexColor('#c7d2fe')),
    ]))

    # push totals to right by padding left
    pad_w = W - 2 * m - sum(totals_w)
    full_row = Table([[Spacer(pad_w, 1), tt]],
                     colWidths=[pad_w, sum(totals_w)])
    full_row.setStyle(TableStyle([('VALIGN', (0, 0), (-1, -1), 'TOP')]))
    story.append(full_row)

    story.append(Spacer(1, 8 * mm))
    story.append(HRFlowable(width='100%', thickness=0.5,
                             color=colors.HexColor('#e2e2ee')))
    story.append(Spacer(1, 4 * mm))

    # payment terms
    story.append(_para('PAYMENT TERMS', size=7.5, bold=True, color=SLATE))
    story.append(Spacer(1, 1 * mm))
    story.append(_para(
        'Payment is due within <b>30 days</b> of the invoice date. '
        'Please reference the invoice number in your payment. '
        'For queries contact accounts@samarthdev.in',
        size=8, color=SLATE
    ))

    # ── 6. Build ───────────────────────────────────────────
    doc.build(story, onFirstPage=draw_header, onLaterPages=draw_header,
              canvasmaker=InvoiceCanvas)

    buf.seek(0)
    return Response(
        buf.read(),
        mimetype='application/pdf',
        headers={
            'Content-Disposition': f'attachment; filename="{inv_num}.pdf"',
            'Content-Type': 'application/pdf',
        }
    )
